# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16aaveqQ7xES0mo8cvlSSXXcRxDERygHP
"""

import random
import time
import matplotlib.pyplot as plt


def linear_search(arr, target):
    for i in range(len(arr)):
        if arr[i] == target:
            return i
    return -1


sizes = [100, 200, 400, 800, 1600, 3200]
linear_times = []

for size in sizes:
    arr = random.sample(range(1, size*10), size)
    start_time = time.time()
    linear_search(arr, arr[random.randint(0, size-1)])
    linear_times.append(time.time() - start_time)


plt.figure(figsize=(10, 6))
plt.plot(sizes, linear_times, label="Linear Search (O(n))", marker='o')
plt.xlabel("Input Size")
plt.ylabel("Time (seconds)")
plt.title("Linear Search Time Complexity")
plt.legend()
plt.grid(True)
plt.show()
